type prevProductRating {
  product: Product
  rating: Float
}
type prevShopRating {
  shop: Shop
  rating: Float
}
type productRating {
  rate: Float!
  totalNumberOfRating: Int!
  ratedProduct: [prevProductRating]
}

type shopRating {
  rate: Float!
  totalNumberOfRating: Int!
  ratedShop: [prevShopRating]
}

type User {
  _id: ID
  firstName: String!
  lastName: String!
  email: String!
  contactNo: String!
  password: String!
  userName: String!
  dateOfBirth: String!
  dateOfRegistration: String
  profilePic: String
  coverPic: String
  role: String
  love: [Product]
  ratedProduct: [productRating]
  ratedShop: [shopRating]
}

type Comment {
  _id: ID
  body: String!
  commentUser: User!
  commentDate: String!
  like: Int
}

type Product {
  _id: ID
  productName: String!
  price: Int!
  description: String!
  comments: [Comment]
  rating: productRating
  tag: [String]!
  category: [String]!
  size: [String]!
  color: [String]!
  parent: String
  discountPrice: Int
  picture: [String]!
  dateOfAdd: String
  shopId: String!
  love: Int
  createdBy: Shop!
}

type Shop {
  _id: ID
  shopName: String!
  owner: User!
  email: String!
  ownerEmail: String!
  contactNo: String!
  address: String!
  dateOfCreation: String
  logo: String
  coverPic: [Carousel]
  rating: shopRating
  shopId: String!
  kudos: Kudos
}

type Carousel {
  _id: ID
  src: String!
  title: String
  button: String
  subtitle: String
  titleColor: String
  subtitleColor: String
  buttonColor: String
}

type Love {
  loves: Int
  wishList: [Product]
}

type Kudos {
  _id: ID
  name: String
  description: String
  year: String
}

type Search {
  product: [Product]
  shop: [Shop]
  user: [User]
}

type Token {
  token: String!
}

type ProductPage {
  products: [Product]
  hasMore: Boolean
}

type OwnRating {
  rating: Float
}

type Address {
  name: String!
  address: String!
  contact: String!
  state: String!
  city: String!
  zip: String!
  country: String!
}
input AddressInput {
  name: String!
  address: String!
  contact: String!
  state: String!
  city: String!
  zip: String!
  country: String!
}

input PurchaseItemInput {
  productItem: ID!
  quantity: Int!
  color: String!
  size: String!
  shopId: ID!
  price: Int!
  shopName: String!
  picture: String!
  productName: String!
}
type PurchaseItem {
  productItem: ID!
  quantity: Int!
  color: String!
  size: String!
  shopId: ID!
  price: Int!
  shopName: String!
  picture: String!
  productName: String!
}
type Order {
  _id: ID
  consumer: ID!
  consumerEmail: String!
  shippingType: String!
  total: Int!
  purchaseItems: [PurchaseItem]!
  address: Address!
  status: String
}

type Query {
  getProducts: [Product]
  getUser(userName: String!): User
  getCurrentUser: User
  getShop(id: String!): Shop
  getAllShopByaUser(id: String!): [Shop]
  getProductsByShopId(id: String!): [Product]
  infiniteScrollProduct(pageNum: Int!, pageSize: Int!): ProductPage!
  getProductByProductId(id: String!): Product!
  searchAny(any: String): Search
  getOwnProductRating(productId: ID!, userId: ID!): OwnRating
  getOrder: [Order]
}

type Mutation {
  addOrder(
    consumer: ID!
    consumerEmail: String!
    shippingType: String!
    total: Int!
    purchaseItems: [PurchaseItemInput]
    address: AddressInput!
  ): Order!

  signup(
    firstName: String!
    lastName: String!
    contactNo: String!
    email: String!
    password: String!
    userName: String
    dateOfBirth: String
  ): Token

  updateProductRating(productId: ID!, userId: ID!, givenRating: Float): Product!

  addCarousel(
    src: String!
    title: String
    button: String
    subtitle: String
    titleColor: String
    subtitleColor: String
    buttonColor: String
    shopId: ID!
  ): Carousel!

  signin(userName: String, password: String!): Token

  addProduct(
    productName: String!
    price: Int!
    description: String!
    tag: [String]
    category: [String]!
    size: [String]!
    color: [String]!
    parent: String
    picture: [String]!
    creatorId: ID!
    shopId: String!
  ): Product!

  createShop(
    shopName: String!
    ownerId: ID!
    ownerEmail: String!
    email: String!
    contactNo: String!
    address: String!
  ): Shop!

  deleteProduct(id: String!): Product!
  loveProduct(productId: ID!, userName: String!): Love!
  unLoveProduct(productId: ID!, userName: String!): Love!
  addComment(body: String, userId: ID, productId: ID): Comment!
}
