export const state = {
  addProductDailog: false,
  shop: null,
  picture: null,
  products: [],
  user: null,
  authError: null,
  loading: false,
  entry: false,
  allShopByaUser: [],
  allShopNameByaUser: null,
  currentShop: null,
  productsByShopId: null,
  productByProductId: null,
  searchResult: null,
  productView: true,
  ownProductRating: null,
  numberOfProduct: null,
  allOrder: null,
  error: null
};
